version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      enabled: false
      threshold: 5
  complex-logic:
    enabled: false
    config:
      threshold: 8
  file-lines:
    enabled: false
    config:
      threshold: 300
  method-complexity:
    enabled: false
    config:
      threshold: 8
  method-count:
    enabled: false
    config:
      threshold: 20
  method-lines:
    enabled: false
    config:
      threshold: 50
  nested-control-flow:
    enabled: false
    config:
      threshold: 6
  return-statements:
    enabled: false
    config:
      threshold: 8
  similar-code:
    enabled: false
  identical-code:
    enabled: false
    config:
      threshold: # language-specific defaults. an override will affect all languages.
exclude_patterns:
- "**/*.test.js"
- "src/serviceWorker.js"
- "src/index.css"
- "src/__tests__/"
plugins:
  editorconfig:
    enabled: true
  csslint:
    enabled: false
    checks:
      box-sizing:
        enabled: false
      fallback-colors:
        enabled: false
      box-model:
        enabled: false
  eslint:
    enabled: true
    config:
      extensions:
        - .js
        - .jsx
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  shellcheck:
    enabled: true
  stylelint:
    enabled: true
